language: node_js

matrix:
  include:
    - os: osx
      node_js: '8'
      sudo: 'required'
before_install:
  - wget https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg 
  - ls googlechrome.dmg
  - ls .
  - hdiutil attach googlechrome.dmg
  - cp -fr /Volumes/*Chrome*/*Chrome* /Applications/chrome.app
install:
  - npm install
  - npm run build
script:
  - npm test
