language: node_js

matrix:
  include:
    - os: osx
      node_js: '12'
      sudo: 'required'
before_install:
  - node .filter-ci.js $TRAVIS_COMMIT
  - wget https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg
  - hdiutil attach googlechrome.dmg
  - cp -R "/Volumes/Google Chrome/Google Chrome.app" /Applications
install:
  - npm install
  - npm run build
script:
  - npm test
