version: 2 
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    working_directory: ~
    docker:
        - image: circleci/node:12.1.0-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm test 
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
